/*
Descripción: PROYECTO FINAL
Fecha: AGOSTO 2022
Equipo:
*Aguilar Brun Mario
*Lizárraga Moreno Ricardo
*Lopez Mora Alan Ignacio
*Meza Borrego Juan Manuel
*Pérez Pérez Joshua Mizraim
*Toledo Becerra Gustavo

 */
package Ventanas_Secundarias_Gerente;

import Metodos_SQL.Conexion_SQL;
import Metodos_SQL.IniciarSesion_BD;
import Ventana_Principales.Empleados;
import static Ventana_Principales.Ventana_Admin.Contenido;
import static Ventana_Principales.Ventana_Gerente.Contenido_Gerente;
import Ventana_Principales_Gerente.Empleados_Gerente;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juani
 */
public class Empleados_Actualizar extends javax.swing.JPanel {
    IniciarSesion_BD bd = new IniciarSesion_BD();
    
    public Empleados_Actualizar() {
        initComponents();
        tablaemp();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Regresar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Agregar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Nombre_txt = new javax.swing.JTextField();
        Apellido_txt = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        Domicilio = new javax.swing.JLabel();
        Domicilio_txt = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        Telefono_txt = new javax.swing.JTextField();
        Priv = new javax.swing.JLabel();
        ID_txt = new javax.swing.JTextField();
        Usuario = new javax.swing.JLabel();
        Fecha_txt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        Fecha1 = new javax.swing.JLabel();
        User_txt = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        pass = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        Pass_txt = new javax.swing.JPasswordField();
        id1 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        priv_comb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        emp = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(13, 71, 171));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Agregar Empleado");

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TituloLayout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(270, 270, 270))
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 100));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Regresar.setBackground(new java.awt.Color(19, 90, 173));
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegresarMousePressed(evt);
            }
        });
        Regresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Regresar");
        Regresar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel1.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 200, 50));

        Agregar.setBackground(new java.awt.Color(19, 90, 173));
        Agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AgregarMousePressed(evt);
            }
        });
        Agregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Actualizar Empleado");
        Agregar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 220, 50));

        Nombre.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        Nombre.setForeground(new java.awt.Color(13, 71, 171));
        Nombre.setText("Nombre:");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        Nombre_txt.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        Nombre_txt.setForeground(new java.awt.Color(204, 204, 204));
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setBorder(null);
        Nombre_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Nombre_txtMousePressed(evt);
            }
        });
        Nombre_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txtActionPerformed(evt);
            }
        });
        Nombre_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nombre_txtKeyTyped(evt);
            }
        });
        jPanel1.add(Nombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 190, -1));

        Apellido_txt.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        Apellido_txt.setForeground(new java.awt.Color(204, 204, 204));
        Apellido_txt.setText("Ingrese un Apellido");
        Apellido_txt.setBorder(null);
        Apellido_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Apellido_txtMousePressed(evt);
            }
        });
        Apellido_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Apellido_txtKeyTyped(evt);
            }
        });
        jPanel1.add(Apellido_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 190, -1));

        Apellido.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        Apellido.setForeground(new java.awt.Color(13, 71, 171));
        Apellido.setText("Apellido:");
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        Domicilio.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        Domicilio.setForeground(new java.awt.Color(13, 71, 171));
        Domicilio.setText("Domicilio:");
        jPanel1.add(Domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        Domicilio_txt.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        Domicilio_txt.setForeground(new java.awt.Color(204, 204, 204));
        Domicilio_txt.setText("Ingrese el Domicilio");
        Domicilio_txt.setBorder(null);
        Domicilio_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Domicilio_txtMousePressed(evt);
            }
        });
        Domicilio_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Domicilio_txtKeyTyped(evt);
            }
        });
        jPanel1.add(Domicilio_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 490, -1));

        Telefono.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        Telefono.setForeground(new java.awt.Color(13, 71, 171));
        Telefono.setText("Telefono:");
        jPanel1.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        Telefono_txt.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        Telefono_txt.setForeground(new java.awt.Color(204, 204, 204));
        Telefono_txt.setText("Ingrese un Telefono");
        Telefono_txt.setBorder(null);
        Telefono_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Telefono_txtMousePressed(evt);
            }
        });
        Telefono_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Telefono_txtKeyTyped(evt);
            }
        });
        jPanel1.add(Telefono_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 210, -1));

        Priv.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        Priv.setForeground(new java.awt.Color(13, 71, 171));
        Priv.setText("Privilegios:");
        jPanel1.add(Priv, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        ID_txt.setEditable(false);
        ID_txt.setBackground(new java.awt.Color(255, 255, 255));
        ID_txt.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        ID_txt.setBorder(null);
        jPanel1.add(ID_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 100, -1));

        Usuario.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        Usuario.setForeground(new java.awt.Color(13, 71, 171));
        Usuario.setText("Usuario:");
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        Fecha_txt.setEditable(false);
        Fecha_txt.setBackground(new java.awt.Color(255, 255, 255));
        Fecha_txt.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        Fecha_txt.setText("Ingrese La Fecha");
        Fecha_txt.setBorder(null);
        Fecha_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Fecha_txtMousePressed(evt);
            }
        });
        Fecha_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Fecha_txtKeyTyped(evt);
            }
        });
        jPanel1.add(Fecha_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 220, -1));

        jSeparator2.setForeground(new java.awt.Color(13, 71, 171));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 190, 10));

        jSeparator3.setForeground(new java.awt.Color(13, 71, 171));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 100, 10));

        jSeparator4.setForeground(new java.awt.Color(13, 71, 171));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 190, 10));

        jSeparator5.setForeground(new java.awt.Color(13, 71, 171));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 490, 10));

        jSeparator6.setForeground(new java.awt.Color(13, 71, 171));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 220, 10));

        jSeparator7.setForeground(new java.awt.Color(13, 71, 171));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 210, 10));

        Fecha1.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        Fecha1.setForeground(new java.awt.Color(13, 71, 171));
        Fecha1.setText("Fecha de Contrato:");
        jPanel1.add(Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        User_txt.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        User_txt.setForeground(new java.awt.Color(204, 204, 204));
        User_txt.setText("Ingrese El Usuario");
        User_txt.setBorder(null);
        User_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                User_txtMousePressed(evt);
            }
        });
        User_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                User_txtKeyTyped(evt);
            }
        });
        jPanel1.add(User_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 220, -1));

        jSeparator8.setForeground(new java.awt.Color(13, 71, 171));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 220, 10));

        pass.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        pass.setForeground(new java.awt.Color(13, 71, 171));
        pass.setText("Contraseña:");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(13, 71, 171));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 220, 10));

        Pass_txt.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        Pass_txt.setForeground(new java.awt.Color(204, 204, 204));
        Pass_txt.setText("********");
        Pass_txt.setBorder(null);
        Pass_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pass_txtMousePressed(evt);
            }
        });
        jPanel1.add(Pass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 220, -1));

        id1.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        id1.setForeground(new java.awt.Color(13, 71, 171));
        id1.setText("ID:");
        jPanel1.add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        jSeparator10.setForeground(new java.awt.Color(13, 71, 171));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 220, 10));

        priv_comb.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        priv_comb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "GERENTE", "EMPLEADO" }));
        priv_comb.setBorder(null);
        jPanel1.add(priv_comb, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, -1));

        emp.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(emp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 190));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 860, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseEntered
        setColor(Agregar);
    }//GEN-LAST:event_AgregarMouseEntered

    private void AgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseExited
       resetColor(Agregar);
    }//GEN-LAST:event_AgregarMouseExited

    private void RegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseEntered
        setColor(Regresar);
    }//GEN-LAST:event_RegresarMouseEntered

    private void RegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseExited
        resetColor(Regresar);
    }//GEN-LAST:event_RegresarMouseExited

    private void RegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMousePressed
        /////REGRESAR A LA SECCION/////
        Empleados_Gerente p1 = new Empleados_Gerente();
        p1.setSize(860, 560);
        p1.setLocation(0,0);
        
        Contenido_Gerente.removeAll();
        Contenido_Gerente.add(p1, BorderLayout.CENTER);
        Contenido_Gerente.revalidate();
        Contenido_Gerente.repaint();
    }//GEN-LAST:event_RegresarMousePressed

    private void Nombre_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txtActionPerformed

    private void Nombre_txtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nombre_txtMousePressed
        //Metodo Cuando Cambiamos de Campo no pierda la estructura 
        if(Nombre_txt.getText().equals("Ingrese un Nombre"))
        Nombre_txt.setText("");
        Nombre_txt.setForeground(Color.black); 
        
        if(String.valueOf(Apellido_txt.getText()).isEmpty()){
        Apellido_txt.setText("Ingrese un Apellido");
        Apellido_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Domicilio_txt.getText()).isEmpty()){
        Domicilio_txt.setText("Ingrese el Domicilio");
        Domicilio_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Telefono_txt.getText()).isEmpty()){
        Telefono_txt.setText("Ingrese un Telefono");
        Telefono_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Fecha_txt.getText()).isEmpty()){
        Fecha_txt.setText("Ingrese La Fecha");
        Fecha_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(User_txt.getText()).isEmpty()){
        User_txt.setText("Ingrese El Usuario");
        User_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Pass_txt.getPassword()).isEmpty()){
        Pass_txt.setText("********");
        Pass_txt.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_Nombre_txtMousePressed

    private void Apellido_txtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Apellido_txtMousePressed
        //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(Apellido_txt.getText().equals("Ingrese un Apellido"))
        Apellido_txt.setText("");
        Apellido_txt.setForeground(Color.black);
        
        if(String.valueOf(Nombre_txt.getText()).isEmpty()){
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Domicilio_txt.getText()).isEmpty()){
        Domicilio_txt.setText("Ingrese el Domicilio");
        Domicilio_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Telefono_txt.getText()).isEmpty()){
        Telefono_txt.setText("Ingrese un Telefono");
        Telefono_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Fecha_txt.getText()).isEmpty()){
        Fecha_txt.setText("Ingrese La Fecha");
        Fecha_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(User_txt.getText()).isEmpty()){
        User_txt.setText("Ingrese El Usuario");
        User_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Pass_txt.getPassword()).isEmpty()){
        Pass_txt.setText("********");
        Pass_txt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_Apellido_txtMousePressed

    private void Domicilio_txtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Domicilio_txtMousePressed

        //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(Domicilio_txt.getText().equals("Ingrese el Domicilio"))
        Domicilio_txt.setText("");
        Domicilio_txt.setForeground(Color.black);
        
        if(String.valueOf(Nombre_txt.getText()).isEmpty()){
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Apellido_txt.getText()).isEmpty()){
        Apellido_txt.setText("Ingrese un Apellido");
        Apellido_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Telefono_txt.getText()).isEmpty()){
        Telefono_txt.setText("Ingrese un Telefono");
        Telefono_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Fecha_txt.getText()).isEmpty()){
        Fecha_txt.setText("Ingrese La Fecha");
        Fecha_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(User_txt.getText()).isEmpty()){
        User_txt.setText("Ingrese El Usuario");
        User_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Pass_txt.getPassword()).isEmpty()){
        Pass_txt.setText("********");
        Pass_txt.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Domicilio_txtMousePressed

    private void Telefono_txtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Telefono_txtMousePressed
        
        
        //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(Telefono_txt.getText().equals("Ingrese un Telefono"))
        Telefono_txt.setText("");
        Telefono_txt.setForeground(Color.black);
        
        if(String.valueOf(Nombre_txt.getText()).isEmpty()){
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Apellido_txt.getText()).isEmpty()){
        Apellido_txt.setText("Ingrese un Apellido");
        Apellido_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Domicilio_txt.getText()).isEmpty()){
        Domicilio_txt.setText("Ingrese el Domicilio");
        Domicilio_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Fecha_txt.getText()).isEmpty()){
        Fecha_txt.setText("Ingrese La Fecha");
        Fecha_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(User_txt.getText()).isEmpty()){
        User_txt.setText("Ingrese El Usuario");
        User_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Pass_txt.getPassword()).isEmpty()){
        Pass_txt.setText("********");
        Pass_txt.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Telefono_txtMousePressed

    private void Fecha_txtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fecha_txtMousePressed

        //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(Fecha_txt.getText().equals("Ingrese La Fecha"))
        Fecha_txt.setText("");
        Fecha_txt.setForeground(Color.black);
        
        if(String.valueOf(Nombre_txt.getText()).isEmpty()){
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Apellido_txt.getText()).isEmpty()){
        Apellido_txt.setText("Ingrese un Apellido");
        Apellido_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Domicilio_txt.getText()).isEmpty()){
        Domicilio_txt.setText("Ingrese el Domicilio");
        Domicilio_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Telefono_txt.getText()).isEmpty()){
        Telefono_txt.setText("Ingrese un Telefono");
        Telefono_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(User_txt.getText()).isEmpty()){
        User_txt.setText("Ingrese El Usuario");
        User_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Pass_txt.getPassword()).isEmpty()){
        Pass_txt.setText("********");
        Pass_txt.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Fecha_txtMousePressed

    private void User_txtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_txtMousePressed
         //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(User_txt.getText().equals("Ingrese El Usuario"))
        User_txt.setText("");
        User_txt.setForeground(Color.black);
        
        if(String.valueOf(Nombre_txt.getText()).isEmpty()){
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Apellido_txt.getText()).isEmpty()){
        Apellido_txt.setText("Ingrese un Apellido");
        Apellido_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Domicilio_txt.getText()).isEmpty()){
        Domicilio_txt.setText("Ingrese el Domicilio");
        Domicilio_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Telefono_txt.getText()).isEmpty()){
        Telefono_txt.setText("Ingrese un Telefono");
        Telefono_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Fecha_txt.getText()).isEmpty()){
        Fecha_txt.setText("Ingrese La Fecha");
        Fecha_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Pass_txt.getPassword()).isEmpty()){
        Pass_txt.setText("********");
        Pass_txt.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_User_txtMousePressed

    private void Pass_txtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pass_txtMousePressed
        
        
        //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(Pass_txt.getText().equals("********"))
            Pass_txt.setText("");
            Pass_txt.setForeground(Color.black);
        
        if(String.valueOf(Nombre_txt.getText()).isEmpty()){
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Apellido_txt.getText()).isEmpty()){
        Apellido_txt.setText("Ingrese un Apellido");
        Apellido_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Domicilio_txt.getText()).isEmpty()){
        Domicilio_txt.setText("Ingrese el Domicilio");
        Domicilio_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Telefono_txt.getText()).isEmpty()){
        Telefono_txt.setText("Ingrese un Telefono");
        Telefono_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Fecha_txt.getText()).isEmpty()){
        Fecha_txt.setText("Ingrese La Fecha");
        Fecha_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(User_txt.getText()).isEmpty()){
        User_txt.setText("Ingrese El Usuario");
        User_txt.setForeground(new Color(204,204,204));
        }    
            
    }//GEN-LAST:event_Pass_txtMousePressed

    private void Nombre_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nombre_txtKeyTyped
        //Metodo Cuando Cambiamos de Campo no pierda la estructura 
        if(Nombre_txt.getText().equals("Ingrese un Nombre"))
        Nombre_txt.setText("");
        Nombre_txt.setForeground(Color.black); 
        
        if(String.valueOf(Apellido_txt.getText()).isEmpty()){
        Apellido_txt.setText("Ingrese un Apellido");
        Apellido_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Domicilio_txt.getText()).isEmpty()){
        Domicilio_txt.setText("Ingrese el Domicilio");
        Domicilio_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Telefono_txt.getText()).isEmpty()){
        Telefono_txt.setText("Ingrese un Telefono");
        Telefono_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Fecha_txt.getText()).isEmpty()){
        Fecha_txt.setText("Ingrese La Fecha");
        Fecha_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(User_txt.getText()).isEmpty()){
        User_txt.setText("Ingrese El Usuario");
        User_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Pass_txt.getPassword()).isEmpty()){
        Pass_txt.setText("********");
        Pass_txt.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Nombre_txtKeyTyped

    private void Apellido_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Apellido_txtKeyTyped
        //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(Apellido_txt.getText().equals("Ingrese un Apellido"))
        Apellido_txt.setText("");
        Apellido_txt.setForeground(Color.black);
        
        if(String.valueOf(Nombre_txt.getText()).isEmpty()){
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Domicilio_txt.getText()).isEmpty()){
        Domicilio_txt.setText("Ingrese el Domicilio");
        Domicilio_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Telefono_txt.getText()).isEmpty()){
        Telefono_txt.setText("Ingrese un Telefono");
        Telefono_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Fecha_txt.getText()).isEmpty()){
        Fecha_txt.setText("Ingrese La Fecha");
        Fecha_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(User_txt.getText()).isEmpty()){
        User_txt.setText("Ingrese El Usuario");
        User_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Pass_txt.getPassword()).isEmpty()){
        Pass_txt.setText("********");
        Pass_txt.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Apellido_txtKeyTyped

    private void Domicilio_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Domicilio_txtKeyTyped
        //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(Domicilio_txt.getText().equals("Ingrese el Domicilio"))
        Domicilio_txt.setText("");
        Domicilio_txt.setForeground(Color.black);
        
        if(String.valueOf(Nombre_txt.getText()).isEmpty()){
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Apellido_txt.getText()).isEmpty()){
        Apellido_txt.setText("Ingrese un Apellido");
        Apellido_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Telefono_txt.getText()).isEmpty()){
        Telefono_txt.setText("Ingrese un Telefono");
        Telefono_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Fecha_txt.getText()).isEmpty()){
        Fecha_txt.setText("Ingrese La Fecha");
        Fecha_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(User_txt.getText()).isEmpty()){
        User_txt.setText("Ingrese El Usuario");
        User_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Pass_txt.getPassword()).isEmpty()){
        Pass_txt.setText("********");
        Pass_txt.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Domicilio_txtKeyTyped

    private void Telefono_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Telefono_txtKeyTyped
        //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(Telefono_txt.getText().equals("Ingrese un Telefono"))
        Telefono_txt.setText("");
        Telefono_txt.setForeground(Color.black);
        
        if(String.valueOf(Nombre_txt.getText()).isEmpty()){
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Apellido_txt.getText()).isEmpty()){
        Apellido_txt.setText("Ingrese un Apellido");
        Apellido_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Domicilio_txt.getText()).isEmpty()){
        Domicilio_txt.setText("Ingrese el Domicilio");
        Domicilio_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Fecha_txt.getText()).isEmpty()){
        Fecha_txt.setText("Ingrese La Fecha");
        Fecha_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(User_txt.getText()).isEmpty()){
        User_txt.setText("Ingrese El Usuario");
        User_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Pass_txt.getPassword()).isEmpty()){
        Pass_txt.setText("********");
        Pass_txt.setForeground(new Color(204,204,204));
        }
        
        //Valida el ingreso de solo numeros
        Character n = evt.getKeyChar();
        
        if(!Character.isDigit(n)){
            evt.consume();
        
        }
        if(Telefono_txt.getText().length() >=10){
            evt.consume();
        }
    }//GEN-LAST:event_Telefono_txtKeyTyped

    private void Fecha_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Fecha_txtKeyTyped
         //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(Fecha_txt.getText().equals("Ingrese La Fecha"))
        Fecha_txt.setText("");
        Fecha_txt.setForeground(Color.black);
        
        if(String.valueOf(Nombre_txt.getText()).isEmpty()){
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Apellido_txt.getText()).isEmpty()){
        Apellido_txt.setText("Ingrese un Apellido");
        Apellido_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Domicilio_txt.getText()).isEmpty()){
        Domicilio_txt.setText("Ingrese el Domicilio");
        Domicilio_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Telefono_txt.getText()).isEmpty()){
        Telefono_txt.setText("Ingrese un Telefono");
        Telefono_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(User_txt.getText()).isEmpty()){
        User_txt.setText("Ingrese El Usuario");
        User_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Pass_txt.getPassword()).isEmpty()){
        Pass_txt.setText("********");
        Pass_txt.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Fecha_txtKeyTyped

    private void User_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_User_txtKeyTyped
        //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(User_txt.getText().equals("Ingrese El Usuario"))
        User_txt.setText("");
        User_txt.setForeground(Color.black);
        
        if(String.valueOf(Nombre_txt.getText()).isEmpty()){
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Apellido_txt.getText()).isEmpty()){
        Apellido_txt.setText("Ingrese un Apellido");
        Apellido_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Domicilio_txt.getText()).isEmpty()){
        Domicilio_txt.setText("Ingrese el Domicilio");
        Domicilio_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Telefono_txt.getText()).isEmpty()){
        Telefono_txt.setText("Ingrese un Telefono");
        Telefono_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Fecha_txt.getText()).isEmpty()){
        Fecha_txt.setText("Ingrese La Fecha");
        Fecha_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Pass_txt.getPassword()).isEmpty()){
        Pass_txt.setText("********");
        Pass_txt.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_User_txtKeyTyped

    private void AgregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMousePressed
  //Metodo para agregar un Producto
        IniciarSesion_BD Emp_up = new IniciarSesion_BD();
        String Nombre = Nombre_txt.getText();
        String Apellido = Apellido_txt.getText();
        String Fecha = Fecha_txt.getText();
        String Direccion = Domicilio_txt.getText();
        String Telefono =Telefono_txt.getText();
        String Usuario = User_txt.getText();
        String Contrasena = Pass_txt.getText();
        String Privilegios = priv_comb.getSelectedItem().toString();
        String id =ID_txt.getText();
        
        if(Nombre.equals("Ingrese un Nombre")||Apellido.equals("Ingrese un Apellido")||Fecha.equals("")||Direccion.equals("Ingrese el Domicilio")||Telefono.equals("Ingrese un Telefono")||Usuario.equals("Ingrese El Usuario")||Contrasena.equals("********")||Privilegios.equals("")||id.equals("")||
                Nombre.equals("")||Apellido.equals("")||Fecha.equals("")||Direccion.equals("")||Telefono.equals("")||Usuario.equals("")||Contrasena.equals("")||Privilegios.equals("")||id.equals("")){
           JOptionPane.showMessageDialog(null, "Por Favor Relleno todos los Campos Son Necesarios");
            Nombre_txt.setText("Ingrese un Nombre");
            Apellido_txt.setText("Ingrese un Apellido");
            Domicilio_txt.setText("Ingrese el Domicilio");
            Telefono_txt.setText("Ingrese un Telefono");
            User_txt.setText("Ingrese El Usuario");
            Pass_txt.setText("********");
        }
        else{
            Emp_up.UPempleado(Nombre,Apellido,Fecha,Direccion,Telefono,Usuario,Contrasena,Privilegios,id);
            JOptionPane.showMessageDialog(this, "Los datos del Empleado fueron Actualizados Correctamente");
            tablaemp();
            Nombre_txt.setText("Ingrese un Nombre");
            Apellido_txt.setText("Ingrese un Apellido");
            Domicilio_txt.setText("Ingrese el Domicilio");
            Telefono_txt.setText("Ingrese un Telefono");
            User_txt.setText("Ingrese El Usuario");
            Pass_txt.setText("********");
        }
    }//GEN-LAST:event_AgregarMousePressed

    private void empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empMouseClicked
        int fila = emp.rowAtPoint(evt.getPoint());
        ID_txt.setText(emp.getValueAt(fila, 0).toString());
        Nombre_txt.setText(emp.getValueAt(fila, 1).toString());
        Apellido_txt.setText(emp.getValueAt(fila, 2).toString());
        Fecha_txt.setText(emp.getValueAt(fila, 3).toString());
        Domicilio_txt.setText(emp.getValueAt(fila, 4).toString());
        Telefono_txt.setText(emp.getValueAt(fila, 5).toString());
        User_txt.setText(emp.getValueAt(fila, 6).toString());
        Pass_txt.setText(emp.getValueAt(fila, 7).toString());
        priv_comb.setSelectedItem(emp.getValueAt(fila, 8).toString());
    }//GEN-LAST:event_empMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agregar;
    private javax.swing.JLabel Apellido;
    private javax.swing.JTextField Apellido_txt;
    private javax.swing.JLabel Domicilio;
    private javax.swing.JTextField Domicilio_txt;
    private javax.swing.JLabel Fecha1;
    private javax.swing.JTextField Fecha_txt;
    private javax.swing.JTextField ID_txt;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField Nombre_txt;
    private javax.swing.JPasswordField Pass_txt;
    private javax.swing.JLabel Priv;
    private javax.swing.JPanel Regresar;
    private javax.swing.JLabel Telefono;
    private javax.swing.JTextField Telefono_txt;
    private javax.swing.JPanel Titulo;
    private javax.swing.JTextField User_txt;
    private javax.swing.JLabel Usuario;
    private javax.swing.JTable emp;
    private javax.swing.JLabel id1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel pass;
    private javax.swing.JComboBox<String> priv_comb;
    // End of variables declaration//GEN-END:variables

    private void setColor(JPanel panel) {
        panel.setBackground(new Color(21,101,192));
    }

    private void resetColor(JPanel panel) {
         panel.setBackground(new Color(18,90,173));
    }
    public String FechaActual(){
        Date fecha = new Date();
        SimpleDateFormat FechaActual = new SimpleDateFormat("YYYY-MM-dd");
        
        return FechaActual.format(fecha);
    
    }
    public void tablaemp(){
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            emp.setModel(modelo);
            PreparedStatement ps = null;
            ResultSet rs = null;
            Connection conectar = Conexion_SQL.getConnection();
            
            String sql = "SELECT * FROM empleados";
            
            ps = conectar.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            
            modelo.addColumn("ID Empleados");
            modelo.addColumn("Nombre Empleado");
            modelo.addColumn("Apellidos Empleado");
            modelo.addColumn("Fecha de Contrato");
            modelo.addColumn("Direccion del Empleado");
            modelo.addColumn("Telefono");
            modelo.addColumn("Usuario");
            modelo.addColumn("Contrasena");
            modelo.addColumn("Privilegio");
            
            
            
            
            
            while(rs.next()){
                
                Object[] filas = new Object[cantidadColumnas];
                for (int i=0; i< cantidadColumnas; i++){
                    filas[i] = rs.getObject(i+1);
                }
                modelo.addRow(filas);
            }
            
        }catch (SQLException ex){
            System.err.println(ex.toString());
            
        }
    
    
    }
}
