/*
Descripción: PROYECTO FINAL
Fecha: AGOSTO 2022
Equipo:
*Aguilar Brun Mario
*Lizárraga Moreno Ricardo
*Lopez Mora Alan Ignacio
*Meza Borrego Juan Manuel
*Pérez Pérez Joshua Mizraim
*Toledo Becerra Gustavo

 */
package Ventanas_Secundarias_Gerente;

import Metodos_SQL.IniciarSesion_BD;
import Ventana_Principales.Clientes;
import Ventana_Principales.Empleados;
import Ventana_Principales.Productos;
import static Ventana_Principales.Ventana_Admin.Contenido;
import static Ventana_Principales.Ventana_Gerente.Contenido_Gerente;
import Ventana_Principales_Gerente.Productos_Gerente;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author juani
 */
public class Productos_Agregar extends javax.swing.JPanel {

    /**
     * Creates new form Empleados
     */
    public Productos_Agregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Regresar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Agregar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Nombre_txt = new javax.swing.JTextField();
        Descripcion_txt = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        Domicilio = new javax.swing.JLabel();
        Precio_txt = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        ID_txt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(13, 71, 171));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Agregar Producto");

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel10)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 100));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Regresar.setBackground(new java.awt.Color(19, 90, 173));
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegresarMousePressed(evt);
            }
        });
        Regresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Regresar");
        Regresar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel1.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 200, 50));

        Agregar.setBackground(new java.awt.Color(19, 90, 173));
        Agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AgregarMousePressed(evt);
            }
        });
        Agregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Agregar Producto");
        Agregar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 200, 50));

        Nombre.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        Nombre.setForeground(new java.awt.Color(13, 71, 171));
        Nombre.setText("Nombre:");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        Nombre_txt.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        Nombre_txt.setForeground(new java.awt.Color(204, 204, 204));
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setBorder(null);
        Nombre_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Nombre_txtMousePressed(evt);
            }
        });
        Nombre_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txtActionPerformed(evt);
            }
        });
        Nombre_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nombre_txtKeyTyped(evt);
            }
        });
        jPanel1.add(Nombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 490, -1));

        Descripcion_txt.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        Descripcion_txt.setForeground(new java.awt.Color(204, 204, 204));
        Descripcion_txt.setText("Ingrese La Descripcion");
        Descripcion_txt.setBorder(null);
        Descripcion_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Descripcion_txtMousePressed(evt);
            }
        });
        Descripcion_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Descripcion_txtActionPerformed(evt);
            }
        });
        Descripcion_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Descripcion_txtKeyTyped(evt);
            }
        });
        jPanel1.add(Descripcion_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 490, -1));

        Apellido.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        Apellido.setForeground(new java.awt.Color(13, 71, 171));
        Apellido.setText("Descripcion:");
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        Domicilio.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        Domicilio.setForeground(new java.awt.Color(13, 71, 171));
        Domicilio.setText("Precio:");
        jPanel1.add(Domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        Precio_txt.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        Precio_txt.setForeground(new java.awt.Color(204, 204, 204));
        Precio_txt.setText("Ingrese el Precio");
        Precio_txt.setBorder(null);
        Precio_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Precio_txtMousePressed(evt);
            }
        });
        Precio_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Precio_txtActionPerformed(evt);
            }
        });
        Precio_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Precio_txtKeyTyped(evt);
            }
        });
        jPanel1.add(Precio_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 490, -1));

        id.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        id.setForeground(new java.awt.Color(13, 71, 171));
        id.setText("ID:");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        ID_txt.setEditable(false);
        ID_txt.setBackground(new java.awt.Color(204, 204, 204));
        ID_txt.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        ID_txt.setBorder(null);
        jPanel1.add(ID_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 210, -1));

        jSeparator2.setForeground(new java.awt.Color(13, 71, 171));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 490, 10));

        jSeparator3.setForeground(new java.awt.Color(13, 71, 171));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 210, 10));

        jSeparator4.setForeground(new java.awt.Color(13, 71, 171));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 490, 10));

        jSeparator5.setForeground(new java.awt.Color(13, 71, 171));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 490, 10));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        jLabel1.setText("$");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 20, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 860, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseEntered
        setColor(Agregar);
    }//GEN-LAST:event_AgregarMouseEntered

    private void AgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseExited
       resetColor(Agregar);
    }//GEN-LAST:event_AgregarMouseExited

    private void RegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseEntered
        setColor(Regresar);
    }//GEN-LAST:event_RegresarMouseEntered

    private void RegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseExited
        resetColor(Regresar);
    }//GEN-LAST:event_RegresarMouseExited

    private void RegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMousePressed
        /////REGRESAR A LA SECCION/////
        Productos_Gerente p = new Productos_Gerente();
        p.setSize(860, 560);
        p.setLocation(0,0);
        
        Contenido_Gerente.removeAll();
        Contenido_Gerente.add(p, BorderLayout.CENTER);
        Contenido_Gerente.revalidate();
        Contenido_Gerente.repaint();
    }//GEN-LAST:event_RegresarMousePressed

    private void Nombre_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txtActionPerformed

    private void Nombre_txtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nombre_txtMousePressed
        //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(Nombre_txt.getText().equals("Ingrese un Nombre"))
        Nombre_txt.setText("");
        Nombre_txt.setForeground(Color.black);
        
        if(String.valueOf(Descripcion_txt.getText()).isEmpty()){
        Descripcion_txt.setText("Ingrese La Descripcion");
        Descripcion_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Precio_txt.getText()).isEmpty()){
        Precio_txt.setText("Ingrese el Precio");
        Precio_txt.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Nombre_txtMousePressed

    private void Descripcion_txtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Descripcion_txtMousePressed

        //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(Descripcion_txt.getText().equals("Ingrese La Descripcion"))
        Descripcion_txt.setText("");
        Descripcion_txt.setForeground(Color.black); 
        
        if(String.valueOf(Nombre_txt.getText()).isEmpty()){
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Precio_txt.getText()).isEmpty()){
        Precio_txt.setText("Ingrese el Precio");
        Precio_txt.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Descripcion_txtMousePressed

    private void Precio_txtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Precio_txtMousePressed

        //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(Precio_txt.getText().equals("Ingrese el Precio"))
        Precio_txt.setText("");
        Precio_txt.setForeground(Color.black); 
        
        if(String.valueOf(Nombre_txt.getText()).isEmpty()){
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Descripcion_txt.getText()).isEmpty()){
        Descripcion_txt.setText("Ingrese La Descripcion");
        Descripcion_txt.setForeground(new Color(204,204,204));
        }
        
        
    }//GEN-LAST:event_Precio_txtMousePressed

    private void Precio_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Precio_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Precio_txtActionPerformed

    private void Descripcion_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Descripcion_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Descripcion_txtActionPerformed

    private void AgregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMousePressed
        //Metodo para agregar un Producto
        IniciarSesion_BD Productos = new IniciarSesion_BD();
        String Nombre = Nombre_txt.getText();
        String Descripcion = Descripcion_txt.getText();
        String Precio = Precio_txt.getText();
        
        if(Nombre.equals("")||Descripcion.equals("")||Precio.equals("")||
                Nombre.equals("Ingrese un Nombre")||Descripcion.equals("Descripcion_txt")||Precio.equals("Ingrese el Precio")){
           JOptionPane.showMessageDialog(null, "Por Favor Relleno todos los Campos Son Necesarios");
        }
        else{
            Productos.AgregarProducto(Nombre,Descripcion,Precio);
            JOptionPane.showMessageDialog(this, "Los datos del Producto fueron Guardados Correctamente");
        }
        
        
        
        
        
        Nombre_txt.setText("");
        Nombre_txt.setForeground(Color.gray);
        
        Descripcion_txt.setText("");
        Descripcion_txt.setForeground(Color.black); 
        
        Precio_txt.setText("");
        Precio_txt.setForeground(Color.gray);
        
        
    }//GEN-LAST:event_AgregarMousePressed

    private void Precio_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Precio_txtKeyTyped
        //Valida el ingreso de solo numeros
        Character n = evt.getKeyChar();
        
        if(!Character.isDigit(n)){
            evt.consume();
        
        }
        if(Precio_txt.getText().length() >=3){
            evt.consume();
        }
        //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(Precio_txt.getText().equals("Ingrese el Precio"))
        Precio_txt.setText("");
        Precio_txt.setForeground(Color.black); 
        
        if(String.valueOf(Nombre_txt.getText()).isEmpty()){
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Descripcion_txt.getText()).isEmpty()){
        Descripcion_txt.setText("Ingrese La Descripcion");
        Descripcion_txt.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Precio_txtKeyTyped

    private void Nombre_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nombre_txtKeyTyped
        //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(Nombre_txt.getText().equals("Ingrese un Nombre"))
        Nombre_txt.setText("");
        Nombre_txt.setForeground(Color.black);
        
        if(String.valueOf(Descripcion_txt.getText()).isEmpty()){
        Descripcion_txt.setText("Ingrese La Descripcion");
        Descripcion_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Precio_txt.getText()).isEmpty()){
        Precio_txt.setText("Ingrese el Precio");
        Precio_txt.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Nombre_txtKeyTyped

    private void Descripcion_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Descripcion_txtKeyTyped
       //Metodo Cuando Cambiamos de Campo no pierda la estructura
        if(Descripcion_txt.getText().equals("Ingrese La Descripcion"))
        Descripcion_txt.setText("");
        Descripcion_txt.setForeground(Color.black); 
        
        if(String.valueOf(Nombre_txt.getText()).isEmpty()){
        Nombre_txt.setText("Ingrese un Nombre");
        Nombre_txt.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(Precio_txt.getText()).isEmpty()){
        Precio_txt.setText("Ingrese el Precio");
        Precio_txt.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Descripcion_txtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agregar;
    private javax.swing.JLabel Apellido;
    private javax.swing.JTextField Descripcion_txt;
    private javax.swing.JLabel Domicilio;
    private javax.swing.JTextField ID_txt;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField Nombre_txt;
    private javax.swing.JTextField Precio_txt;
    private javax.swing.JPanel Regresar;
    private javax.swing.JPanel Titulo;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables

    private void setColor(JPanel panel) {
        panel.setBackground(new Color(21,101,192));
    }

    private void resetColor(JPanel panel) {
         panel.setBackground(new Color(18,90,173));
    }
}
